### ISSUE TITLE
Query: How to ensure one message goes to one worker

### ISSUE THREAD

**Issue by geoff-ellison** [tomaj/hermes#23]
Hi,

First, thank you for this very useful project.

I would like to use Hermes in a scaled-out environment with a centralised Redis server (AWS ElastiCache), and multiple server instances, all running multiple workers.

In the [Scaling Hermes](https://github.com/tomaj/hermes#scaling-hermes) section, you mentioned that two things are essential:

> 1. driver needs to be able to work over network

I've got this covered with Redis.

> 2. one message must be delivered to only one worker

There will be multiple workers registered, across multiple servers, and the emitting script will simply emit a message, without really knowing where it is going. How do I ensure that the message reaches only one worker?

Is there anything else I should be aware of that might cause issues in a scaled-out environment like this?

Many thanks

Geoff.

**Comment by tomaj** [comment]
Hi

About redis driver. This driver in hermes library (RedisSetDriver) is  implemented to use redis set as storage key type (https://redis.io/commands#set). This will ensure that one message will be delivered only to one worker - worker send command `spop` to redis and redis deliver one message from set and discard this message, so no other worker will get it.

I am also using this driver in distributed environments and it performs very well.

There is only one issue with redis - right now with RedisSetDriver your not able to process different type of Messages with different workers. This is possible only with create 2 dispatchers/emitters and use different keys in redis for each set. 

Hope this will help you. If you need more information or some help please let me know.

Regards
tomaj

**Comment by geoff-ellison** [comment]
Hi @tomaj,

Thanks very much for your reply, that covers my situation.

> There is only one issue with redis - right now with RedisSetDriver your not able to process different type of Messages with different workers. This is possible only with create 2 dispatchers/emitters and use different keys in redis for each set.

This isn't a problem, I'll keep to one message type and put logic in the workers to decide (based on parameters in the payload) if they need to do some different handling.

Cheers

Geoff.
