### ISSUE TITLE
Split RedisDriver to 2 separated drivers

### ISSUE THREAD

**Issue by tomaj** [tomaj/hermes#40]

**Comment by lulco** [comment]
Redis and Predis? You can use RedisProxy :) https://github.com/lulco/redis-proxy/blob/master/src/RedisProxy.php

**Comment by tomaj** [comment]
i would like to get rid of all these if statements where we have determine if it is for one or the other implementation. there are also type differences for example in  `sadd` method where phpstan complain in level 5

it will be much cleaner i think

**Comment by lulco** [comment]
RedisProxy solves this - it has common API for both implementations - same parameters, same errors. If statements are hidden :)
